- plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
#5 Adds according hidden output for the check, that uses the highest possible prefix.
> Add Output usage for UsedPartition

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckService.psm1
We incorrectly included the wildcard name on the service args to match against our found services. We should exclude wildcard names which contain '*'
Fixes #79
> Fix: IcingaCheckService with wildcard includes service name with wildcard in checkresult

- doc/31-Changelog.md
- doc/plugins/16-Invoke-IcingaCheckUsedPartitionSpace.md
- plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
- provider/disks/Icinga_ProviderDisks.psm1
Fixes `Invoke-IcingaCheckUsedPartitionSpace` to throw an unknown in case permissions for certain partitions are missing and no data can be fetched. This resolves an issue for partitions reporting 100% usage.
> Fix: Throw unknown in case partition data cant be read

- doc/31-Changelog.md
- provider/cpu/Icinga_ProviderCpu.psm1
Fixes `Get-IcingaCPUCount` returns wrong count on empty arguments
> Fix: Get-IcingaCPUCount returns wrong count on empty arguments

- doc/31-Changelog.md
- doc/plugins/13-Invoke-IcingaCheckService.md
- plugins/Invoke-IcingaCheckService.psm1
- provider/services/Add-IcingaServiceSummary.psm1
- provider/services/New-IcingaWindowsServiceCheckObject.psm1
Improves the documentation and output for `Invoke-IcingaCheckService` by adding metrics for all found services configured to run `Automatic` and adds service output on Verbosity 1 to show a list of all found services including their current state
Fixes #78
> Fix: Improves documentation and output for Invoke-IcingaCheckService

- doc/31-Changelog.md
- doc/plugins/16-Invoke-IcingaCheckUsedPartitionSpace.md
- plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
We should add support to ignore empty check packages in case we filtered all partitions out on the check. This might be required in certain scenarios and can be very helpful.
In addition it might be helpful to convert Unknown partition data to Ok for not causing false positives.
> Feature: Add support to ignore empty checks on UsedPartitionSpace plugin and ignore Unknowns

- doc/plugins/04-Invoke-IcingaCheckCPU.md
- plugins/Invoke-IcingaCheckCPU.psm1
Adds documentation on how to monitor avg. CPU load on all cores only.
#93
> Doc: Adds documentation for monitoring avg. load on all cores for CPU plugin

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckScheduledTask.psm1
- provider/enums/Icinga_ProviderEnums.psm1
Fixes `Invoke-IcingaCheckScheduledTask` performance data output by using integer states instead of the string state names.
> Fix: Invoke-IcingaCheckScheduledTask returns invalid perf data output

- doc/31-Changelog.md
- doc/plugins/20-Invoke-IcingaCheckDiskHealth.md
- plugins/Invoke-IcingaCheckDiskHealth.psm1
Adds two new argumengs to `Invoke-IcingaCheckDiskHealth`, `-IgnoreOfflineDisks` and `-IgnoreReadOnlyDisks` which will ignore disks which are either in the `Offline` or `Read Only` state and returns `Ok` instead of `Warning` once the new flags are set.
> Feature: Adds support to ignore read only/offline disks on Invoke-IcingaCheckDiskHealth

- doc/31-Changelog.md
- doc/plugins/21-Invoke-IcingaCheckNetworkInterface.md
- plugins/Invoke-IcingaCheckNetworkInterface.psm1
Fixes `Invoke-IcingaCheckNetworkInterface` plugins arguments being too long for Icinga Director
> Fix: Invoke-IcingaCheckNetworkInterface plugin args are too long

- doc/30-Upgrading-Plugins.md
- doc/31-Changelog.md
Updates changelog and upgrading docs
> Docs: Updates upgrading/changelog docs

- doc/30-Upgrading-Plugins.md
- doc/31-Changelog.md
Improves `Invoke-IcingaCheckScheduledTask` by changing the `State` argument from `String` to `Array`, allowing the comparison against multiple states. **Important:** Please have a look on the [upgrading docs!](https://icinga.com/docs/windows/latest/plugins/doc/30-Upgrading-Plugins/)
> Feature: Changed Invoke-IcingaCheckScheduledTask to support multi States

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckCheckSum.psm1
Adds exception handling in case `-Path` argument is not set or not directing a file (including invalid path)
> Fix: Adds exception handling for checksum plugin

- doc/31-Changelog.md
- provider/eventlog/Get-IcingaEventLog.psm1
Fixes EventLog plugin throwing an unknown for valid arguments:
```powershell
icinga { Invoke-IcingaCheckEventlog '-Warning' '5' '-Critical' '10' '-LogName' 'Application' '-IncludeEventId' '@()' '-ExcludeEventId' '@()' '-IncludeUsername @() -IncludeEntryType @() -ExcludeEntryType @() -IncludeMessage @() -ExcludeMessage @() -IncludeSource @() -ExcludeSource @() }
```
```text
[UNKNOWN]: Icinga Invalid Input Error was thrown: EventLog
Failed to fetch EventLog information. Please check your inputs for EntryTypes and other categories and try again.
```
> Fix: Eventlog throwing unknown on valid arguments

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckService.psm1
Fixes #121
There was an error on the `-Service` argument while creating the service check object for services which should run automatically.
> Fix: Service Check crashes on automatic service not running

- doc/31-Changelog.md
- provider/enums/Icinga_ProviderEnums.psm1
- provider/services/Icinga_ProviderServices.psm1
In some cases, it can happen that `Get-Service` which is used primarily to fetch most of the service data, is not providing any results of the startup type of the service. This results in an error on the plugin, as the monitoring of all services which should be running `Automatic` and throw a critical if not exited properly is no longer possible. The result is simply "Ok" with no services checked as the status code is always 0 for all services and not matching the actual comparison value of 2 (Automatic)
> Fix: Prefer startup type of services fetching over WMI instead of Get-Services

- plugins/Invoke-IcingaCheckTCP.psm1
Instead of using `ConvertTo-SecondsFromIcingaThresholds` we should use `Convert-IcingaPluginThresholds` for converting our plugin thresholds for `Invoke-IcingaCheckTCP`.
> Fix TCP plugin, use Convert-IcingaPluginThresholds

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckUptime.psm1
Adds check note for the last boot time which is being displayed by using `-Verbosity 2` on the check configuration.
```
[OK] Check package "System Uptime: 8d 1h 28m 50s" (Match All)
\_ [OK] Last Boot: 02/16/2021 08:50:45
\_ [OK] System Uptime: 696530.888485s
```
Fixes #122
> Feature: Adds last boot time to uptime check as notice

- doc/31-Changelog.md
- provider/services/Icinga_ProviderServices.psm1
While filtering for certain services with `Get-IcingaServices`, there were some attributes missing from the collection. These are now added resulting in always correct output data.
> Fixes missing attributes for services

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
Fixes a copy & paste error on `Invoke-IcingaCheckUsedPartitionSpace`, as a wrong check variable was used for forcing `Unknown`.
> Fix: Copy & paste error in variable naming on Invoke-IcingaCheckUsedPartitionSpace

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckPerfcounter.psm1
Fixes wrong OK states for Performance Counter check, in case counters for categories with instances were not present
> Fix: Print UNKNOWN in case Perf Counter do not exist for instance counters

- plugins/Invoke-IcingaCheckHTTPStatus.psm1
The states for the check HTTP plugin were not correct for alerting on the content matches and the entire package itself
> Fix: Check HTTP package states

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckNLA.psm1
Fixes exception hanlding for `Invoke-IcingaCheckNLA` to properly handle errors while checking for connection profiles
> Fix: Improves exception handling for check NLA

- doc/31-Changelog.md
- provider/ntp/Get-IcingaNtpData.psm1
Fixes offset calculation for `Invoke-IcingaCheckTimeSync`, to allow negative offset as well
Fixes #176
> Fix: Time offset calculation for Invoke-IcingaCheckTimeSync should allow negative offset

- doc/31-Changelog.md
- provider/network/Get-IcingaNetworkDeviceInfo.psm1
Fixes exception on `Invoke-CheckNetworkInterface` while two team interfaces with the identical name are present on the system
Fixes #148
> Fix: Exception on Invoke-CheckNetworkInterface on duplicate team interface

- doc/31-Changelog.md
- icinga-powershell-plugins.psm1
Fixes possible exception on Icinga for Windows installation, if plugins were removed, no new shell session was created and threfor plugins are not able to load
> Fix: Exception on plugin import on deleted plugin folder

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
Fixes `\` and `/` which are now removed again for `-Include` and `-Exclude` arrays.
> Fix: Slahes for Invoke-IcingaCheckUsedPartitionSpace are removed again

- doc/31-Changelog.md
- provider/directory/Icinga_Provider_Directory.psm1
- provider/enums/IcingaGeneralPlugins_Exceptions.psm1
Fixes unhandled PermissionDenied exceptions for `Invoke-IcingaCheckDirectory`, in case required permissions for files and folders were not set
Fixes #196
> Fix: PermissionDenied exception on Invoke-IcingaCheckDirectory

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckCheckSum.psm1
We have to replace `Get-FileHash` which is a native PowerShell implementation for `Get-IcingaFileHash` as custom implementation, to ensure plugins using this function are working properly in JEA context.
> Feature: Replaces Get-FileHash with own implementation

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
Fixes label name for `Invoke-IcingaCheckUsedPartitionSpace`, by renaming them from `partition_{0}` back to `used_space_partition_{0}`, as otherwise we run into metric displaying issues with Graphite/InfluxDB.
> Fix: UsedPartitionSpace plugin had wrong label name for partitions

- doc/31-Changelog.md
- provider/enums/Icinga_ProviderEnums.psm1
- provider/http/Get-IcingaCheckHTTPQuery.psm1
- provider/ntp/Get-IcingaNtpData.psm1
In order for the plugins to work in JEA context, we will have to get rid of all `ScriptBlocks` and replace them with native functions.
> Feature: Updates Plugin module to work in JEA context

- doc/31-Changelog.md
- provider/disks/Get-IcingaDiskAttributes.psm1
- provider/disks/Get-IcingaUNCPathSize.psm1
Fixes class names of `Add-Type` for `Get-IcingaDiskAttributes` and `Get-IcingaUNCPathSize`.
Also adds checks if the class was already added inside the context
> Fix: Class names for Add-Type and check if class was already added

- doc/31-Changelog.md
- provider/disks/Get-IcingaDiskAttributes.psm1
In case the main partition of Windows has no space left, the Invoke-IcingaCheckUsedPartitionSpace plugin returned falsely UNKNOWN because of internal exceptions being catched.
This fix will now always ensuse that in this case, the plugin witll return CRITICAL with a basic message that no space is left on the partition, as there are no other information available during this state.
Fixes #200
> FIx: Invoke-IcingaCheckUsedPartitionSpace returns UNKNOWN instead of CRITICAL on case partition has no space left

- doc/31-Changelog.md
- provider/disks/Get-IcingaDiskPartitionAssignment.psm1
Fixes `Invoke-IcingaCheckUsedPartitionSpace` in case mirrored disks are used within the system, causing an exception on duplicate partition id's
Fixes #187
> Fix: Mirrored disk partition exception

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckService.psm1
While using the service display name for `Invoke-IcingaCheckService`, the correct service is added, but also an unknown because we only checked if the service is present by it's name instead of the display name.
This will now resolve this issue and allow the monitoring by using the name and the display name with proper results.
> Fix: Wrong UNKNOWN while using service display name

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
The alias for `Invoke-IcingaCheckUsedPartitionSpace` is not working on Windows 2012R2 and older. Therefor we replace it with a native function, calling our new plugin name,
Fixes #250
> Fix: Partition Space Plugin alias not Working on 2012R2

- doc/31-Changelog.md
- provider/eventlog/Get-IcingaEventLog.psm1
Fixes method NULL exception on empty EventLog entries, as the `Message` is directly processed within check handler, not ensuring that the string actually contains a valid string and not `$null`.
> Fix: Method NULL exception on empty EventLog

- doc/31-Changelog.md
- provider/disks/Get-IcingaPartitionSpace.psm1
Fixes an error for JEA profile generation which wrongly detected a string formatting as `ScriptBlock`.
> Fix: Code causing JEA error for ScriptBlocks

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckTimeSync.psm1
The plugin `Invoke-IcingaCheckTimeSync` was previously not saved as `UTF8`, causing it to not being loaded properly by the JEA manager of Icinga for Windows.
> Fix: File encoding to UTF8 for TimeSync plugin

- plugins/Invoke-IcingaCheckProcess.psm1
Fixes the wrong process count for `Invoke-IcingaCheckProcess`, which was the thread count before.
> Fix: Wrong process count number for process check

- doc/31-Changelog.md
- provider/tasks/Get-IcingaScheduledTask.psm1
Fixes `Invoke-IcingaCheckScheduledTask` for wildcard task names, which added the unknown package in case wildcards were used for task names
Fixes #274
> Fix: Invoke-IcingaCheckScheduledTask wildcard task names

- doc/31-Changelog.md
- icinga-powershell-plugins.psd1
- provider/disks/Get-IcingaDiskAttributes.psm1
- provider/disks/Get-IcingaUNCPathSize.psm1
Icinga for Windows is using Add-Type in some small cases, to properly fetch UNC Path values for plugins or disk attribute information.
While in most cases this works without problems, sometimes the on-the-fly compilation fails because of out-of-memory exceptions or different errors.
This fix will now compile the DLL required inside the cache/dll folder if not present and load the compiled DLL's if required and available by using the new Framework function `Add-IcingaAddTypeLib`
> Fix: Add-Type exceptions during runtime compilation

- doc/31-Changelog.md
- provider/http/Get-IcingaCheckHTTPQuery.psm1
Fixes `Invoke-IcingaCheckHTTPStatus` which is not returning the request time, in case the target website is not providing content
Fixes #286
> Fix: Invoke-IcingaCheckHTTPStatus RequestTime return value

- doc/31-Changelog.md
- icinga-powershell-plugins.psd1
- provider/private/services/Get-IcingaServiceCheckName.psm1
Fixes function `Get-IcingaServiceCheckName` which was not public anymore since v1.9.0, causing MSSQL plugins to not work properly
> Fix: Non-public function Get-IcingaServiceCheckName

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckCheckSum.psm1
Removes performance data for `Invoke-IcingaCheckCheckSum`, as there are no real performance metrics to write which are allowed by icinga.
> Fix: Removes performance metric for CheckSum plugin

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckService.psm1
- provider/private/services/Add-IcingaServiceSummary.psm1
Fixes `Invoke-IcingaCheckService` to write invalid performance data in case one service is actively checked and returning `UNKNOWN` because it does not exist
#322
> Fix: Invalid perf data for service plugin

- doc/31-Changelog.md
- provider/memory/Get-IcingaMemoryPerformanceCounter.psm1
Fixes the pagefile provider at `Get-IcingaMemoryPerformanceCounter` which returned the pagefile size in MB instead of Bytes
Fixes https://github.com/Icinga/icinga-powershell-framework/issues/617
> Fix: Pagefile provider returning values in MB instead of Bytes

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckMemory.psm1
Fixes `Invoke-IcingaCheckMemory` which uses the wrong unit for the pagefile plugin, wrong values, exceptions and %-Values not working
Fixes #338
Fixes #359
Fixes #360
> Fix: Pagefile unit for memory plugin

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckService.psm1
Fixes `Invoke-IcingaCheckService` to not add summary performance metrics in case the user filtered for specific services
> Fix: `Invoke-IcingaCheckService` to properly include summary metrics for filtered services

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckService.psm1
Fixes an issue with service names not interpreted correctly by `Invoke-IcingaCheckService` in case it contains `[]`
Fixes #398
> Fix: Service plugin for brackets in service names

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckCPU.psm1
Removes process list feature for `Invoke-IcingaCheckCPU`, which causes too much CPU overhead and increase execution time by a lot without substantial gain of information
Fixes #418
> Fix: Removes process list for `Invoke-IcingaCheckCPU`

- doc/31-Changelog.md
- provider/directory/Icinga_Provider_Directory.psm1
Fixes `Invoke-IcingaCheckDirectory` which could not resolve `-Path` arguments in case closing `[` or open brackets `]` were part of the path
Fixes #401
> Fix: `Invoke-IcingaCheckDirectory` not working with brackets in path

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckPerfcounter.psm1
Fixes `Invoke-IcingaCheckPerfCounter` to write correct performance data in case only certain instances are checked to ensure perf data are assigned to checks accordingly
Fixes #377
> Fix: Invoke-IcingaCheckPerfCounter to always write proper assigned perf data

- doc/31-Changelog.md
- plugins/Invoke-IcingaCheckUptime.psm1
Fixes `Invoke-IcingaCheckUptime` to report a more human readable output for the current uptime in the package name
Fixes #420
> Fix: Invoke-IcingaCheckUptime to report a more human readable output for the current uptime in the package name
